/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,html}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#eaddff',
        'on-primary-container': '#ede0ff',
        'on-tertiary-container': '#ffe0cd',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-variant': '#e3dfff',
        'on-surface': '#181445',
        outline: '#7b7487',
        tertiary: '#7d3d00',
        'outline-variant': '#ccc3d8',
        'surface-container-low': '#f6f2ff',
        'surface-container': '#efebff',
        secondary: '#8127cf',
        'tertiary-container': '#a15100',
        'surface-dim': '#dad6ff',
        'tertiary-fixed': '#ffdcc6',
        'on-secondary-fixed': '#2c0051',
        'on-tertiary-fixed': '#301400',
        'secondary-fixed-dim': '#ddb7ff',
        'on-tertiary-fixed-variant': '#713700',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f3eeff',
        surface: '#fcf8ff',
        'on-primary-fixed': '#25005a',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed-variant': '#5a00c6',
        'surface-container-highest': '#e3dfff',
        'on-background': '#181445',
        'surface-container-high': '#e9e5ff',
        'on-surface-variant': '#4a4455',
        'secondary-container': '#9c48ea',
        'inverse-surface': '#2d2a5b',
        'on-secondary-container': '#fffbff',
        'surface-bright': '#fcf8ff',
        'on-secondary-fixed-variant': '#6900b3',
        'inverse-primary': '#d2bbff',
        'surface-tint': '#732ee4',
        primary: '#630ed4',
        background: '#fcf8ff',
        'secondary-fixed': '#f0dbff',
        'primary-container': '#7c3aed',
        'tertiary-fixed-dim': '#ffb784',
        'on-primary': '#ffffff',
        success: '#10B981',
        'success-container': '#D1FAE5',
        'electric-purple': '#8A2BE2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'stack-xs': '4px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'stack-xl': '80px',
      },
      fontFamily: {
        display: ['Geist', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'headline-lg': ['Geist', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'headline-md': ['Geist', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'body-lg': ['Inter', 'Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Geist', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'label-sm': ['Geist', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['64px', { lineHeight: '72px', letterSpacing: '-0.04em' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.01em' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      keyframes: {
        'route-fade': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'route-fade': 'route-fade 260ms ease-out both',
      },
    },
  },
  plugins: [],
};
